theme: jekyll-theme-cayman
title: Project 3
description: Create a "coinage" code module that is capable of calculating the total value of coin objects. After completing the "coinage" code module functionality, you will then update the "server" code file as a true Node.js web server using the Fastify package.
